### ISSUE TITLE
Should use Codable for JSON parsing / encoding

### ISSUE THREAD

**Issue by mluisbrown** [Mindera/Alicerce#119]
Since Swift 4.0 introduced [Codable](https://developer.apple.com/documentation/swift/codable) the library should use it instead of custom JSON parsing via `Mappable`.

**Comment by p4checo** [comment]
hi @mluisbrown 👋 

Thanks for opening this issue! You're absolutely right, and we should deprecate `Mappable` in favor of `Codable` 😉 

In fact, we've had this improvement on our TODO list but haven't tackled it yet.
I think I'll migrate that list to Issues so that it's visible to everyone.

Cheers! 🍻

**Comment by marcosgriselli** [comment]
@p4checo are you guys accepting PRs? I'd love to contribute to the `Codable` migration if added as a public issue.

**Comment by p4checo** [comment]
hi @marcosgriselli! 🤝 

Thanks for your interest! And yes, we do accept PR's 😄 

Since no one is currently working on this, we would really appreciate if someone could give us a hand! 
Please take a look at our [CONTRIBUTING](https://github.com/Mindera/Alicerce/blob/master/CONTRIBUTING.md) for our guidelines on PR's.

Should I assign you this, then? 😜 

Cheers! 🍻
