### ISSUE TITLE
Clear `viewModel` on `prepareForReuse` when using `ReusableViewModelView`

### ISSUE THREAD

**Issue by diogoeiras** [Mindera/Alicerce#203]
As the title implies, should we clear the `viewModel` on `prepareForReuse` when inheriting from `ReusableViewModelView`? With this, we would guarantee that the view/cell is on a pristine state when used again. It should be straightforward to implement as we only need to override `prepareForReuse` and set the `viewModel` to `nil`.

**Comment by p4checo** [comment]
This is a cool idea! 👍 

However, I think that we should probably do this on our **base cells/reusable views**, and not on our **base protocols**. The reason is that the actual wiring (e.g. calling `setUpBindings` when the VM is set) is already done on actual implementations, and this behavior fits under the same category.

So, in practice we could have default `prepareForReuse` implementations that set the `viewModel = nil` on:
- `ViewModelCollectionViewCell`
- `ViewModelCollectionReusableView`
-  `TableViewCell`
- `ViewModelTableViewHeaderFooterView`

That way both the VM _set_ and _unset_ are in the same place ✨ 

Regarding your suggestion to change `ReusableViewModelView`, we _could_ add a `prepareForReuse` method to `ReusableViewModelView`, but it would only be useful for any custom views that are reusable and don't inherit from CollectionView/TableView cells/views. Then we could even create a protocol extension with a "default" `prepareForReuse` implementation that resets the VM, but we would still be missing the `setUpBindings` call on the VM's `didSet`, so it would be an "incomplete" Implementation. That being said, I think it's probably not worth it to change the `ReusableViewModelView` protocol, and simply perform the changes on the base cells/views.

Hope this made sense 😜
